major additions for #368

diff --git a/steamtinkerlaunch b/steamtinkerlaunch
--- a/steamtinkerlaunch
+++ b/steamtinkerlaunch
@@ -6,7 +6,7 @@
 PREFIX="/usr"
 PROGNAME="SteamTinkerLaunch"
 NICEPROGNAME="Steam Tinker Launch"
-PROGVERS="v8.1.20220106"
+PROGVERS="v8.1.20220107"
 PROGCMD="${0##*/}"
 SHOSTL="stl"
 GHURL="https://github.com"
@@ -276,6 +276,7 @@ SGDBSTYOPTS="alternate,blurred,white_logo,material,no_logo"
 STLGAMES="$STLCFGDIR/games"
 STLGDESKD="$STLGAMES/desktop"
 STLIDFD="$STLGAMES/desktopfiles"
+STLISLDFD="$STLGAMES/sldesktopfiles"
 STLAPPINFOIDDIR="$STLGAMES/$APIN"
 STLGHEADD="$STLGAMES/header"
 STLGSAD="$STLGAMES/standalone"
@@ -799,20 +800,46 @@ function createDesktopIconFile {
 	fi
 
 	WANTGPNG="$STLGPNG/${AID}.png"
-	INTDTFILE="$STLIDFD/$AID.desktop"
+
+	if [ "$STLPLAY" -eq 1 ]; then
+		mkProjDir "$STLISLDFD"
+		INTDTFILE="$STLISLDFD/$AID.desktop"
+	else
+		INTDTFILE="$STLIDFD/$AID.desktop"
+	fi
 
 	if [ -f "$INTDTFILE" ]; then
 		writelog "INFO" "${FUNCNAME[0]} - Already have an internal desktop file '$INTDTFILE'"
 	else
 		if [ -n "$AID" ] && [ ! -f "$WANTGPNG" ]; then
 			writelog "INFO" "${FUNCNAME[0]} - Don't have a desktop icon yet - trying to create it"
-			getGameIcon
+			if [ "$STLPLAY" -eq 1 ]; then
+				if [ -n "$4" ]; then
+					GAMENAME="$3"
+					HAVEPA="$4"
+					standaloneGameIcon "$WANTGPNG" "$AID" "$GAMENAME" "$HAVEPA"
+				else
+					writelog "WARN" "${FUNCNAME[0]} - Not enough arguments passes to create an icon - got '$*'"
+				fi
+			else
+				getGameIcon
+			fi
 		fi
 
 		# create desktop file internally for optionally using it on the desktop
 		if [ -f "$WANTGPNG" ] && [ ! -f "$INTDTFILE" ]; then
 			writelog "INFO" "${FUNCNAME[0]} - Creating $INTDTFILE"
-			writeDesktopFile "$AID" "$INTDTFILE" "$WANTGPNG"
+			if [ "$STLPLAY" -eq 1 ]; then
+				if [ -n "$4" ]; then
+					GAMENAME="$3"
+					HAVPA="$4"
+					standaloneDesktopFile "$INTDTFILE" "$WANTGPNG" "$AID" "$GAMENAME" "$HAVEPA"
+				else
+					writelog "WARN" "${FUNCNAME[0]} - Not enough arguments passes to create a desktopfile - got '$*'"
+				fi
+			else
+				writeDesktopFile "$AID" "$INTDTFILE" "$WANTGPNG"
+			fi
 		fi
 	fi
 
@@ -1824,7 +1851,7 @@ function getGameOS {
 				writelog "INFO" "${FUNCNAME[0]} - STEAM_COMPAT_DATA_PATH is defined - This is no longer necessarily a reliable indication that this is a Windows game."
 				if [ -f "$OSCHECKGAMEEXE" ]; then
 					writelog "INFO" "${FUNCNAME[0]} - Making some more checks on '$OSCHECKGAMEEXE' to determine the OS version of the game"
-					if grep -q "POSIX shell script" <<< "$(file "$OSCHECKGAMEEXE")" || grep -q "ELF.*.LSB" <<< "$(file "$OSCHECKGAMEEXE")" ; then
+					if grep -q "shell script" <<< "$(file "$(realpath "$OSCHECKGAMEEXE")")" || grep -q "ELF.*.LSB" <<< "$(file "$(realpath "$OSCHECKGAMEEXE")")" ; then
 						writelog "INFO" "${FUNCNAME[0]} - Looks like this is a Linux game!"
 						setLin "$@"
 					elif grep -q "PE32" <<< "$(file "$OSCHECKGAMEEXE")"; then
@@ -3398,7 +3425,9 @@ function CustomFallbackPicture {
 }
 
 function setShowPic {
-	if [ "$USEGAMEPICS" -eq 1 ]; then
+	if [ "$STLPLAY" -eq 1 ] && [ -f "$STLGPNG/${AID}.png" ]; then
+		SHOWPIC="$STLGPNG/${AID}.png"
+	elif [ "$USEGAMEPICS" -eq 1 ]; then
 		writelog "INFO" "${FUNCNAME[0]} - Determining game picture"
 		if [ -s "$STLGHEADD/$AID.jpg" ]; then
 			SHOWPIC="$STLGHEADD/$AID.jpg"
@@ -7169,28 +7198,32 @@ function installReshade {
 			CHARCH="$GP"
 		fi
 
-		#32bit:
-		if [ "$(getArch "$CHARCH")" == "32" ]; then
-			writelog "INFO" "${FUNCNAME[0]} - Installing 32bit ${RESH} as '$CHARCH' is 32bit" 
-			#d3d47
-			installd3d47dll "$D3D47_32" "$INSTDESTDIR"
-			#dxgi:
-			installRSdll "$RS_DX_DEST" "0" "$RS_32"
-			#d3d9:
-			installRSdll "$RS_D9_DEST" "$NOD3D9" "$RS_32"
+		if [ -d "$INSTDESTDIR" ]; then
+			#32bit:
+			if [ "$(getArch "$CHARCH")" == "32" ]; then
+				writelog "INFO" "${FUNCNAME[0]} - Installing 32bit ${RESH} as '$CHARCH' is 32bit" 
+				#d3d47
+				installd3d47dll "$D3D47_32" "$INSTDESTDIR"
+				#dxgi:
+				installRSdll "$RS_DX_DEST" "0" "$RS_32"
+				#d3d9:
+				installRSdll "$RS_D9_DEST" "$NOD3D9" "$RS_32"
 
-		# 64bit:
-		elif [ "$(getArch "$CHARCH")" == "64" ]; then
-			writelog "INFO" "${FUNCNAME[0]} - Installing 64bit ${RESH} as '$CHARCH' is 64bit" 
-			#d3d47
-			installd3d47dll "$D3D47_64" "$INSTDESTDIR"
-			#dxgi:
-			installRSdll "$RS_DX_DEST" "0" "$RS_64"
-			#d3d9:
-			installRSdll "$RS_D9_DEST" "$NOD3D9" "$RS_64"
+			# 64bit:
+			elif [ "$(getArch "$CHARCH")" == "64" ]; then
+				writelog "INFO" "${FUNCNAME[0]} - Installing 64bit ${RESH} as '$CHARCH' is 64bit" 
+				#d3d47
+				installd3d47dll "$D3D47_64" "$INSTDESTDIR"
+				#dxgi:
+				installRSdll "$RS_DX_DEST" "0" "$RS_64"
+				#d3d9:
+				installRSdll "$RS_D9_DEST" "$NOD3D9" "$RS_64"
+			else
+				writelog "SKIP" "${FUNCNAME[0]} - ERROR in ${RESH} installation - no file information detected for '$CHARCH' or any 'neighbor file' - setting USERESHADE=0 for this session"
+				export USERESHADE=0
+			fi
 		else
-			writelog "SKIP" "${FUNCNAME[0]} - ERROR in ${RESH} installation - no file information detected for '$CHARCH' or any 'neighbor file' - setting USERESHADE=0 for this session"
-			export USERESHADE=0
+			writelog "SKIP" "${FUNCNAME[0]} - INSTDESTDIR '$INSTDESTDIR' not found" 
 		fi
 	fi
 }
@@ -10397,7 +10430,7 @@ function downloadCheatEngine {
 	# yes I know 7.3 is released - proper PR accepted, I won't spend more time on CE generally
 	CHEATENGINEURLEVAL="$CHEATENGINEURL/download/$CHEATENGINEVERSION/$CESET"
 	if [ "$CHEATENGINEVERSION" == "7.2" ]; then
-		writelog "WARNING" "${FUNCNAME[0]} - Cheat Engine upstream removed version 7.2 - defaulting to wayback machine archive"
+		writelog "WARN" "${FUNCNAME[0]} - Cheat Engine upstream removed version 7.2 - defaulting to wayback machine archive"
 		CHEATENGINEURLEVAL="$CEWAYBACKURL/$CHEATENGINEURLEVAL"
 	fi
 	CESET="$1"
@@ -13269,7 +13302,7 @@ function checkPev {
 							cd "$PEVDSTI" >/dev/null || return
 							notiShow "$(strFix "$NOTY_ANALYZE" "$GE" "$PEVCMD")"
 							"$PEVCMD" -x "$GP" &
-							cd "$PEVDSTI" >/dev/null || return
+							cd - >/dev/null || return
 						else
 							writelog "SKIP" "${FUNCNAME[0]} - $USEPEV is enabled, but already have files in '$PEVDSTI'"
 						fi
@@ -13372,7 +13405,7 @@ function prepareLaunch {
 	# in case a path changed in between, call createProjectDirs again:
 	createProjectDirs
 
-	createDesktopIconFile "$AID" "0"
+	
 
 	# autoapply configuration settings based on the steam categories the game is in:
 	autoCategorySettings
@@ -13605,7 +13638,7 @@ function switchProton {
 }
 
 function prepareProtonDBRating {
-	if [ "$USEPDBRATING" ]; then
+	if [ "$USEPDBRATING" ] && [ "$STLPLAY" -eq 0 ]; then
 		PDBRAINFO="$STLSHM/PTB-${AID}.txt"
 		PDBRASINF="${PDBRAINFO//-/short-}"
 
@@ -14456,7 +14489,6 @@ function fixCustomMeta {
 }
 
 function initPlay {
-	#XXXXXXXXXXXXXXXXX - far from being functional - early wip
 	HAVESLR=0
 	HAVESLRCT=0
 	HAVEREAP=0
@@ -14499,6 +14531,63 @@ function initPlay {
 			loadCfg "$HAVGACO"
 			LOADEDHAVGACO=1
 		fi
+	}
+
+	function saveHaveCuMe {
+		if [ ! -f "$HAVCUME" ]; then
+			touch "$HAVCUME"
+		fi
+		
+		if [ -n "$MEGAMEDIR" ]; then 
+			touch "$FUPDATE"
+			updateConfigEntry "MEGAMEDIR" "$MEGAMEDIR" "$HAVCUME"
+		fi
+	}
+
+	function saveHaveGeMe {
+		if [ ! -f "$HAVGEME" ]; then
+			touch "$HAVGEME"
+		fi
+
+		if [ -n "$HAVID" ]; then
+			touch "$FUPDATE"
+			updateConfigEntry "GAMEID" "$HAVID" "$HAVGEME"
+		elif [ -n "$AID" ] && [ "$AID" != "$PLACEHOLDERAID" ]; then
+			touch "$FUPDATE"
+			updateConfigEntry "GAMEID" "$AID" "$HAVGEME"
+		fi
+		
+		if [ -n "$EXECUTABLE" ]; then 
+			touch "$FUPDATE"
+			updateConfigEntry "EXECUTABLE" "$EXECUTABLE" "$HAVGEME"	
+			if [ -z "$GAMEEXE" ]; then
+				GAMEEXE="${EXECUTABLE//.exe}"
+			fi
+		fi
+
+		if [ -n "$GE" ] && [ -z "$GAMEEXE" ]; then
+			GAMEEXE="$GE"
+		fi
+
+		if [ -n "$GAMEEXE" ]; then
+			touch "$FUPDATE"
+			updateConfigEntry "GAMEEXE" "$GAMEEXE" "$HAVGEME"
+		fi
+
+		if [ -z "$GAMENAME" ]; then
+			GAMENAME="${EXECUTABLE//.exe}"
+		fi
+			
+		if [ -n "$GAMENAME" ]; then
+			touch "$FUPDATE"
+			updateConfigEntry "GAMENAME" "$GAMENAME" "$HAVGEME"
+		fi
+
+		if [ -z "$KEEPGAMENAME" ]; then
+			KEEPGAMENAME=1
+			touch "$FUPDATE"
+			updateConfigEntry "KEEPGAMENAME" "$KEEPGAMENAME" "$HAVGEME"
+		fi	
 	}
 
 	if [ "$1" -eq "$1" ] 2>/dev/null; then
@@ -14570,8 +14659,6 @@ function initPlay {
 	
 	if [ -n "$EXECUTABLE" ] && [ -n "$HAVPA" ] && [ "$EXECUTABLE" != "${HAVPA##*/}" ]; then
 		EXECUTABLE="${HAVPA##*/}"
-		touch "$FUPDATE"
-		updateConfigEntry "EXECUTABLE" "$EXECUTABLE" "$HAVGEME"
 	fi
 
 	if [ -n "$MEGAMEDIR" ]; then
@@ -14590,11 +14677,10 @@ function initPlay {
 
 	if [ -n "$MEGAMEDIR" ] && [ -n "$HAVPA" ] && [ "$MEGAMEDIR" != "${HAVPA%/*}" ]; then
 		MEGAMEDIR="${HAVPA%/*}"
-		GFD="${HAVPA%/*}"
-		EFD="${HAVPA%/*}"
-		touch "$FUPDATE"
-		updateConfigEntry "MEGAMEDIR" "$MEGAMEDIR" "$HAVCUME"		
 	fi
+
+	if [ -n "${HAVPA%/*}" ] && [ -z "$EFD" ]; then EFD="${HAVPA%/*}"; fi
+	if [ -n "${HAVPA%/*}" ] && [ -z "$GFD" ]; then GFD="${HAVPA%/*}"; fi
 
 	setHaveConfs
 	loadHaveConfs
@@ -14609,12 +14695,28 @@ function initPlay {
 		AID="$GAMEID"
 	fi
 
+	saveHaveCuMe
+	saveHaveGeMe
+    # from here all required vars should be ready to launch
+
 	if [ -n "$AID" ] && [ "$AID" != "$PLACEHOLDERAID" ]; then
 		if [ -z "$HAVGACO" ]; then
 			HAVGACO="$STLGAMEDIRID/$AID.conf"
 		fi
 
 		loadHaveConfs
+
+		if [ -n "$GAMENAME" ] && [ "$GAMENAME" != "$NON" ]; then
+			ICGN="$GAMENAME"
+		elif [ -n "$GAMEEXE" ] && [ "$GAMEEXE" != "$NON" ]; then
+			ICGN="$GAMEEXE"
+		elif [ -n "$EXECUTABLE" ] && [ "$EXECUTABLE" != "$NON" ]; then
+			ICGN="$GAMEEXE"
+		else
+			ICGN="$NON"
+		fi
+
+		createDesktopIconFile "$AID" "0" "$ICGN" "$HAVPA"
 
 		if [ -f "$HAVPA" ]; then
 			if [ -z "$GP" ]; then
@@ -14658,7 +14760,7 @@ function initPlay {
 
 			writelog "INFO" "${FUNCNAME[0]} - Game executable used is '$HAVPA'" "E"
 
-			if grep -q "POSIX shell script" <<< "$(file "$OSCHECKGAMEEXE")" || grep -q "ELF.*.LSB" <<< "$(file "$HAVPA")" ; then
+			if grep -q "shell script" <<< "$(file "$(realpath "$HAVPA")")" || grep -q "ELF.*.LSB" <<< "$(file "$(realpath "$HAVPA")")" ; then
 				writelog "INFO" "${FUNCNAME[0]} - Assuming this is a linux binary" "E"
 				ISGAME=3
 				GPFX="$NON"
@@ -14695,6 +14797,147 @@ function initPlay {
 	else
 		writelog "ERROR" "${FUNCNAME[0]} - Could not determine an AppID - can't continue" "E"
 	fi
+}
+
+function standaloneGames {
+	if [ -d "$GEMETA" ]; then
+		while read -r line; do
+			if [ -n "$1" ] && [ "$1" == "l" ]; then
+				SAG="$(grep "^GAMENAME=" "$line" | cut -d '=' -f2)"
+				if [ -n "$SAG" ]; then
+					echo "${SAG//\"/}"
+				fi
+			elif [ -n "$1" ] && [ "$1" == "g" ]; then
+				unset GAMENAME EXECUTABLE GAMEID
+				loadCfg "$line"
+				if [ -n "$GAMEID" ] && [ -n "$EXECUTABLE" ]; then
+					echo "FALSE"
+
+					if [ -n "$GAMENAME" ]; then
+						echo "$GAMENAME"
+					else
+						echo "$EXECUTABLE"
+					fi
+					
+					echo "$EXECUTABLE"
+					echo "$GAMEID"
+				else
+					writelog "SKIP" "${FUNCNAME[0]} - Skipping config '$line', because at least one of GAMEID:'$GAMEID' EXECUTABLE:'$EXECUTABLE', GAMENAME:'$GAMENAME' is empty"
+				fi
+			else
+				echo "$line"
+			fi
+		done <<< "$(find "$GEMETA" -name "99[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]99.conf")"
+	else
+		writelog "ERROR" "${FUNCNAME[0]} - Directory GEMETA '$GEMETA' could not be found" "E"
+ 	fi
+}
+
+function standaloneGameIcon {
+	WANTGPNG="$1"
+	AID="$2"
+	GAMENAME="$3"
+	HAVEPA="$4"
+	if [ -f "$WANTGPNG" ]; then
+		writelog "SKIP" "${FUNCNAME[0]} - Already have an icon: '$WANTGPNG'"
+	else
+		writelog "SKIP" "${FUNCNAME[0]} - Trying to find an icon for '$GAMENAME'"
+		if grep -q "shell script" <<< "$(file "$(realpath "$HAVPA")")" || grep -q "ELF.*.LSB" <<< "$(file "$(realpath "$HAVPA")")" ; then
+			# yes, quick&dirty!
+			SYSICN="$(cut -d '=' -f2 <<< "$(grep "^Icon=" "$(find "/usr/share/applications/" -name "${HAVPA##*/}*.desktop" | head -n1)")")"
+			if [ -n "$SYSICN" ]; then
+				SYSICF="$(find "/usr/share/icons/" -name "${SYSICN}.png" | sort -nr | head -n1)"
+				if [ -f "$SYSICF" ]; then
+					if [ -x "$(command -v "$CONVERT" 2>/dev/null)" ]; then
+						writelog "INFO" "${FUNCNAME[0]} - Creating a '$SYSICF' copy with fix size 128x128 at '$WANTGPNG'"
+						"$CONVERT" "$SYSICF" -resize "128x128!" "$WANTGPNG"
+					else
+						writelog "INFO" "${FUNCNAME[0]} - Copying '$SYSICF' to '$WANTGPNG'"
+						cp "$SYSICF" "$WANTGPNG"
+					fi
+				else
+					writelog "INFO" "${FUNCNAME[0]} - Did not find a default icon for '$GAMENAME' using '$STLICON' as default for '$WANTGPNG'"
+					if [ -x "$(command -v "$CONVERT" 2>/dev/null)" ]; then
+						"$CONVERT" "$STLICON" -resize "128x128!" "$WANTGPNG"
+					else
+						cp "$STLICON" "$WANTGPNG"
+					fi
+				fi
+			fi
+		else
+			PEVDSTI="$STLGPEVKD/$PERES/id/$AID"
+			
+			if [ -x "$(command -v "$PERES")" ] && { [ ! -d "$PEVDSTI" ] || [ "$(find "$PEVDSTI" -type f | wc -l)" -eq 0 ];}; then
+				mkProjDir "$PEVDSTI"
+				writelog "INFO" "${FUNCNAME[0]} - extracting data from '${HAVEPA##*/}' using '$PERES' to '$PEVDSTI'"
+				cd "$PEVDSTI" >/dev/null || return
+				notiShow "$(strFix "$NOTY_ANALYZE" "$HAVEPA" "$PERES")"
+				"$PERES" -x "$HAVEPA" &
+				cd - >/dev/null || return
+			fi
+			
+			FIRSTICO="$(find "$PEVDSTI/resources/icons" -type f -name "*.ico" -printf "%s %p\n" | sort -nr | head -n1 | cut -d ' ' -f2)"
+
+			if [ -f "$FIRSTICO" ]; then
+				if [ -x "$(command -v "$CONVERT" 2>/dev/null)" ]; then
+					writelog "INFO" "${FUNCNAME[0]} - Converting '$FIRSTICO', extracted from '${HAVEPA##*/}' to '$WANTGPNG'"
+					"$CONVERT" "$FIRSTICO" -resize "128x128!" "$WANTGPNG"
+				else
+					writelog "INFO" "${FUNCNAME[0]} - Could not convert '$FIRSTICO', because '$CONVERT' was not found - using '$STLICON' as default for '$WANTGPNG'"
+					cp "$STLICON" "$WANTGPNG"
+				fi
+			else
+				writelog "INFO" "${FUNCNAME[0]} - Could not extract icon from '${HAVEPA##*/}' - using '$STLICON' as default for '$WANTGPNG'"
+				if [ -x "$(command -v "$CONVERT" 2>/dev/null)" ]; then
+					"$CONVERT" "$STLICON" -resize "128x128!" "$WANTGPNG"
+				else
+					cp "$STLICON" "$WANTGPNG"
+				fi
+			fi
+		fi	
+	fi
+}
+
+function standaloneDesktopFile {
+	INTDTFILE="$1"
+	WANTGPNG="$2"
+	AID="$3"
+	GAMENAME="$4"
+
+	if [ -f "$INTDTFILE" ]; then
+		writelog "SKIP" "${FUNCNAME[0]} - $INTDTFILE already exists"
+	else
+		if [ -n "$GAMENAME" ] && [ "$GAMENAME" != "$NON" ]; then
+			{
+				echo "[Desktop Entry]"
+				echo "Name=${GAMENAME//\"/}"
+				echo "Comment=$(strFix "$DF_SLCOMMENT" "${GAMENAME//\"/}" "$PROGNAME")"
+				echo "Exec=$(realpath "$0") play $AID"
+				echo "Icon=$WANTGPNG"
+				echo "Terminal=false"
+				echo "Type=Application"
+				echo "Categories=Game;"
+			} >> "$INTDTFILE"
+		fi
+	fi
+}
+
+function standaloneLaunch {
+	setShowPic
+	STLA="Standalone-Launcher"
+	export CURWIKI="$PPW/$STLA"
+	TITLE="${PROGNAME}-$STLA"
+	pollWinRes "$TITLE"
+	
+	if [ -d "$STLISLDFD" ] && [ "$(find "$STLISLDFD" -name "*.desktop" | wc -l)" -ge 1 ]; then
+		"$YAD" --f1-action="$F1ACTION" --icons --window-icon="$STLICON" --read-dir="$STLISLDFD" "$WINDECO" --title="$TITLE" --single-click --keep-icon-size --center --compact --sort-by-name "$GEOM"
+	else
+		writelog "SKIP" "${FUNCNAME[0]} - No games found in '$STLISLDFD' or directory itself not found"
+	fi
+}
+
+function standaloneEd {
+	writelog "INFO" "${FUNCNAME[0]} - Not implemented " "E"
 }
 
 function createDLWineList {
@@ -15860,9 +16103,15 @@ function commandline {
 		pickGameWindowNameMeta "$2" "$3"
 	elif [ "$1" == "play" ]; then
 		if [ -z "$2" ]; then
-			writelog "INFO" "${FUNCNAME[0]} - need at a valid game name or SteamAppId of an installed game or an absolute path to a game exe as arg2 '$2'" "E"
+			writelog "INFO" "${FUNCNAME[0]} - need at a valid game name or SteamAppId of an installed game or an absolute path to a game exe as arg2 '$2' or 'gui' for a menu" "E"
 		else
-			initPlay "${@:2}"
+			if [ "$2" == "gui" ]; then
+				standaloneLaunch
+			elif [ "$2" == "ed" ]; then
+				standaloneEd "${@:2}"
+			else
+				initPlay "${@:2}"
+			fi
 		fi
 	elif [ "$1" == "proton" ] || [ "$1" == "p" ]; then
 		StandaloneProtonGame "$2" "$3"
@@ -16123,7 +16372,11 @@ function storeMetaData {
 	
 	loadCfg "$GEMETA/$MAID.conf" X
 	updateConfigEntry "GAMEID" "$MAID" "$GEMETA/$MAID.conf"
-	updateConfigEntry "GAMENAME" "$MGNA" "$GEMETA/$MAID.conf"
+
+	if [ -z "$KEEPGAMENAME" ] || [ "$KEEPGAMENAME" -eq 0 ] || [ "$GAMENAME" == "$NON" ]; then
+		updateConfigEntry "GAMENAME" "$MGNA" "$GEMETA/$MAID.conf"
+	fi
+
 	if [ -n "$GE" ] && [ -z "$GAMEEXE" ]; then
 		GAMEEXE="$GE"
 	fi
